### ISSUE TITLE
Updating Version Number doesn't work anymore

### ISSUE THREAD

**Issue by icexuick** [spring/upq#63]
When i update a map to a new version, the version number doesn't get saved anymore.
New file is saved, as is the description, but not the version number.

**Comment by springraaar** [comment]
I got the same issue when editing an existing uploaded file for my game, replacing the file and updating the version number : the file was replaced but the old version number was kept.

Workaround is to just make a new upload.

**Comment by icexuick** [comment]
Yeah - that's an option - but without its showing up in the API list people still need to manually download it.

**Comment by abma** [comment]
i don't see this beeing fixed at any point: a rewrite of springfiles.com is what will come but with a very limited feature set at the beginning.

see #64 for the progress.
