### ISSUE TITLE
Can't upload new map files anymore

### ISSUE THREAD

**Issue by icexuick** [spring/upq#64]
Everytime i want to upload a new map, the form gets cleared and nothing happens.
I've tried 5 times, doing this in a different order, but it doesn't work.

**Comment by abma** [comment]
can you please test if https://api.springfiles.com/upload/ works for you?

(if not, please copy/paste the output here)

thank you!

after the upload, the game/map should instant show up at https://api.springfiles.com/

source: https://github.com/spring/upq/blob/master/www/upload/index.py

**Comment by icexuick** [comment]
I get wrong username/password for both springrts and springfiles user/pass combis

**Comment by icexuick** [comment]
I tried some login combinations.. last one worked :)

This is the output:

symlinking /tmp/springfiles-upload/BarR.sd7 /home/upq/upq/tmp/tmp4v3jtymu/games/BarR.sd7
using unitsync version 100
SDP 6c866fa6fa6de71535fc6d5084b12623
Wrote /home/upq/upq/metadata/f27c6be71ffa776198cb3ee7eed9009f.jpg
mapname: BarR 1.1 513x513
Wrote /home/upq/upq/metadata/232c2d36133e1461861bde2f8b4eaac6.jpg
mapname: BarR 1.1 256x256
Wrote /home/upq/upq/metadata/b659da903647b44cbee2a0f9758611c0.jpg
moved file to (abs)/tmp/springfiles-upload/BarR.sd7 :(rel)/home/upq/upq/files/maps/barr_1.1.sd7
moved file to /home/upq/upq/files/maps/barr_1.1.sd7
{'Type': 'map', 'Author': 'IceXuick, original from ralphie', 'Description': 'Barren Remake | BAR Certified', 'Gravity': 110, 'MaxWind': 19, 'MinWind': 3, 'TidalStrength': 20, 'Height': 8.0, 'Width': 8.0, 'MapFileName': 'maps/BarR.smf', 'MapMinHeight': 0.0, 'MapMaxHeight': 0.0, 'Resources': [{'Name': 'Metal', 'Max': 0.3400000035762787, 'ExtractorRadius': 120}], 'Units': [], 'StartPos': [{'x': 262.0, 'z': 180.0}, {'x': 3752.0, 'z': 3932.0}, {'x': 180.0, 'z': 901.0}, {'x': 3834.0, 'z': 3211.0}], 'mapimages': ['f27c6be71ffa776198cb3ee7eed9009f.jpg', '232c2d36133e1461861bde2f8b4eaac6.jpg', 'b659da903647b44cbee2a0f9758611c0.jpg'], 'path': 'maps', 'splash': []}
INSERT INTO file (uid, filename, path, size, status, timestamp, md5, sha1, sha256, name, version, cid, sdp, metadata) VALUES (%s, %s, %s, %s, %s, now(), %s, %s, %s, %s, %s, %s, %s, %s) ({'name': 'BarR 1.1', 'version': '', 'sdp': '6c866fa6fa6de71535fc6d5084b12623', 'cid': 1, 'metadata': '{"Type": "map", "Author": "IceXuick, original from ralphie", "Description": "Barren Remake | BAR Certified", "Gravity": 110, "MaxWind": 19, "MinWind": 3, "TidalStrength": 20, "Height": 8.0, "Width": 8.0, "MapFileName": "maps/BarR.smf", "MapMinHeight": 0.0, "MapMaxHeight": 0.0, "Resources": [{"Name": "Metal", "Max": 0.3400000035762787, "ExtractorRadius": 120}], "Units": [], "StartPos": [{"x": 262.0, "z": 180.0}, {"x": 3752.0, "z": 3932.0}, {"x": 180.0, "z": 901.0}, {"x": 3834.0, "z": 3211.0}], "mapimages": ["f27c6be71ffa776198cb3ee7eed9009f.jpg", "232c2d36133e1461861bde2f8b4eaac6.jpg", "b659da903647b44cbee2a0f9758611c0.jpg"], "path": "maps", "splash": []}', 'uid': 0, 'path': 'maps', 'filename': 'barr_1.1.sd7', 'timestamp': <sqlalchemy.sql.functions.now at 0x7fc0f3aafa00; now>, 'size': 70852633, 'status': 1, 'md5': '81b2a7b7f684d55a4472eb59dd44cfbd', 'sha1': '0f3289585bdd8ff69ce9979b49c5f9c258923000', 'sha256': '3f80d09bf6158276b80ff6df70ad9c30ad70d93f88b783bd4a8e988405660e3a'}) id:133333
Updated map 'BarR 1.1' version '' sdp '6c866fa6fa6de71535fc6d5084b12623' in the mirror-system
File doesn't exist: /tmp/springfiles-upload/BarR.sd7
b'ProcessUnits: luaParser.Execute() failed: could not open file: gamedata/defs.lua'

**Comment by icexuick** [comment]
File seems to appear on api.springfiles and possible to download!
Will need some further testing if it's correct

**Comment by abma** [comment]
yes, the log output is fine!

its not user friendly atm: the messages are for debugging, i will try to improve that.

glad, that it worked for you, too. thanks!
